# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "develop", "release/**" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest 
    if: github.ref != 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and test Docker image
      run: | 
        docker build --target test -f Dockerfile -t internal-source-load:test . --no-cache
        docker run --rm internal-source-load:test
        
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build production Docker image
      run: docker build --target runtime -t internal-source-load:latest .

    - name: Build Database Docker image
      run: docker build --build-arg DB_PASSWORD=root -t database:latest -f Database .

    - name: Save Database Docker image to tar file
      run: docker save -o database.tar database:latest

    - name: Upload Database Docker image tar file
      uses: actions/upload-artifact@v4
      with:
        name: database-tar
        path: database.tar

    - name: Save Docker image to tar file
      run: docker save -o internal-source-load.tar internal-source-load:latest

    - name: Upload Docker image tar file
      uses: actions/upload-artifact@v4
      with:
        name: internal-source-load-tar
        path: internal-source-load.tar